spring:
  application:
    name: config-server
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/configdb
    username: navsingh3211
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT  PROP_KEY,PROP_VALUE FROM PROPERTIES WHERE APPLICATION=? AND PROFILE=? AND LABEL=?"
          default-label: main
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/navsingh3211/cxp-config
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}

server:
  port: 8888